# Generated by Django 4.1.7 on 2023-04-04 00:27

from django.db import migrations

def populate_status(apps, schemaeditor):
    defaults = {
        "To Do": "issues that have not yet been started",
        "In Progress": "Issues that are actively being worked on",
        "Done": "Completed issues"
    }
    Status = apps.get_model("issues", "Status")
    for key, desc in defaults.items():
        status_obj = Status(name=key, description=desc)
        status_obj.save()

def populate_priority(apps, schemaeditor):
    defaults ={
        "Low": "A low priority item",
        "Medium": "An item of medium priority",
        "High": "An important or high priority item"
    }
    Priority = apps.get_model("issues", "Priority")
    for key, desc in defaults.items():
        priority_obj = Priority(name=key, description=desc)
        priority_onj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status),
        migrations.RunPython(populate_priority)
    ]
